- uses: athul/waka-readme@master
  with:
    WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
    SHOW_OS: "true"
    SHOW_EDITORS: "true"
    SHOW_CATEGORIES: "true"
    SHOW_LANGUAGES: "true"
    OS_RANGE: "all_time"  # Special setting for OS stats
    TIME_RANGE: "last_30_days"
    BLOCKS: "▁▂▃▄▅▆▇█"
    SECTION_HEADER: "## ⌨️ Development Analytics"
