name: Update WakaTime Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Daily update
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false

      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          SHOW_TITLE: false
          BLOCKS: "▁▂▃▄▅▆▇█"
          TIME_RANGE: "last_30_days"
          LANG_COUNT: 5  # Show top 5 languages
          SHOW_TIME: "true"
          COMMIT_MESSAGE: "Update WakaTime Stats"
