name: Update WakaTime Stats
on:
  schedule:
    - cron: '0 0 * * *'  # Daily update
  workflow_dispatch:

jobs:
  update-readme:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Update Stats
        uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          SHOW_OS: "true"
          SHOW_EDITORS: "true"
          SHOW_LANGUAGE: "true"
          SHOW_TIMEZONE: "false"
          SHOW_PROJECTS: "false"
          COMMIT_MESSAGE: "📊 Updated WakaTime Stats"
